---
# You can override vars by using host or group vars

###########
# GENERAL #
###########

fetch_directory: fetch/

# Even though RGW nodes should not have the admin key
# at their disposal, some people might want to have it
# distributed on RGW nodes. Setting 'copy_admin_key' to 'true'
# will copy the admin key to the /etc/ceph/ directory
copy_admin_key: false

## Ceph options
#
cephx: true

# Used for the sudo exception while starting the radosgw process
# a new entry /etc/sudoers.d/ceph will be created
# allowing root to not require tty
radosgw_user: root
