---
# You can override vars by using host or group vars

###########
# GENERAL #
###########

fetch_directory: fetch/

## Ceph options
#
cephx: true

# Used for the sudo exception while starting the radosgw process
# a new entry /etc/sudoers.d/ceph will be created
# allowing root to not require tty
radosgw_user: root
