---
# You can override vars by using host or group vars

###########
# GENERAL #
###########

fetch_directory: fetch/

# Even though MDS nodes should not have the admin key
# at their disposal, some people might want to have it
# distributed on MDS nodes. Setting 'copy_admin_key' to 'true'
# will copy the admin key to the /etc/ceph/ directory
copy_admin_key: false

cephx: true
