---
- name: generate ceph configuration file
  action: config_template
  args:
    src: "{{ role_path }}/templates/ceph.conf.j2"
    dest: /etc/ceph/ceph.conf
    owner: "root"
    group: "root"
    mode: "0644"
    config_overrides: "{{ ceph_conf_overrides }}"
    config_type: ini
