---
###########
# GENERAL #
###########

fetch_directory: fetch/

user_config: false
pools:
  - { name: test, pgs: "{{ pool_default_pg_num }}" }
  - { name: test2, pgs: "{{ pool_default_pg_num }}" }

keys:
  - { name: client.test, value: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=test'" }
  - { name: client.test2, value: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=test2'" }
