---
- name: fail on unsupported system
  fail:
    msg: "System not supported {{ ansible_system }}"
  when: "'{{ ansible_system }}' not in ['Linux']"

- name: fail on unsupported architecture
  fail:
    msg: "Architecture not supported {{ ansible_architecture }}"
  when: "'{{ ansible_architecture }}' not in ['x86_64', 'ppc64le']"

- name: fail on unsupported distribution
  fail:
    msg: "Distribution not supported {{ ansible_os_family }}"
  when: "'{{ ansible_os_family }}' not in ['Debian']"

- name: fail on unsupported ansible version
  fail:
    msg: "Ansible version must be >= 1.9, please update!"
  when:
    - ansible_version.major|int == 1
    - ansible_version.minor|int < 9
