---
- name: install dependencies
  apt:
    pkg: calamari-server
    state: present
  when: ansible_os_family == 'Debian'
  tags:
    - package-install

- name: create minion.d directory
  file:
    path: /etc/salt/minion.d
    state: directory

- name: generate agent configuration file
  template:
    src: ceph_agent.j2
    dest: /etc/salt/minion.d/ceph_agent.conf
