---
- include: deploy_monitors.yml

- include: start_monitor.yml

- include: ceph_keys.yml

- include: create_mds_filesystems.yml
  when:
    groups[mds_group_name] is defined

- include: secure_cluster.yml
  when:
    secure_cluster and
