---
- name: activate monitor with upstart
  file:
    path: /var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }}/{{ item }}
    state: touch
    owner: "{{ activate_file_owner }}"
    group: "{{ activate_file_group }}"
    mode: "{{ activate_file_mode }}"
  changed_when: false
  with_items:
    - done
    - upstart
  when: not use_systemd

- name: start and add that the monitor service to the init sequence (ubuntu)
  command: initctl emit ceph-mon cluster={{ cluster }} id={{ monitor_name }}
  changed_when: false
  failed_when: false
  when: not use_systemd

# NOTE (leseb): somehow the service ansible module is messing things up
# as a safety measure we run the raw command
- name: start and add that the monitor service to the init sequence
  command: service ceph start mon
  changed_when: false
  when:
    - ansible_distribution != "Ubuntu"
    - is_before_infernalis

- name: start and add that the monitor service to the init sequence (for or after infernalis)
  command: systemctl enable ceph-mon@{{ monitor_name }}
  changed_when: false
  failed_when: false
  when:
    - use_systemd
    - is_after_hammer

- name: start the monitor service (for or after infernalis)
  service:
      name: ceph-mon@{{ monitor_name }}
      state: started
      enabled: yes
  changed_when: false
  when:
    - use_systemd
    - is_after_hammer

- name: collect admin and bootstrap keys
  command: ceph-create-keys --cluster {{ cluster }} --id {{ monitor_name }}
  changed_when: false
  failed_when:  false
  when: cephx
