---
- name: check if rgw is started
  command: /etc/init.d/radosgw status
  register: rgwstatus
  changed_when: false
  failed_when: false

- name: start rgw
  command: /etc/init.d/radosgw start
  when:
    rgwstatus.rc != 0 and
    ansible_distribution != "Ubuntu" and
    ansible_os_family != 'RedHat'

- name: start and add that the rados gateway service to the init sequence (ubuntu)
  command: initctl emit radosgw cluster={{ cluster }} id=rgw.{{ ansible_hostname }}
  changed_when: false
  failed_when: false
  when: ansible_distribution == 'Ubuntu'

- name: enable systemd unit file for rgw instance (for or after infernalis)
  file:
    src: /usr/lib/systemd/system/ceph-radosgw@.service
    dest: /etc/systemd/system/multi-user.target.wants/ceph-radosgw@rgw.{{ ansible_hostname }}.service
    state: link
  changed_when: false
  failed_when: false
  when:
    ansible_distribution != "Ubuntu" and
    is_ceph_infernalis

- name: start rgw on ubuntu
  service:
    name: radosgw
    name: ceph-radosgw@rgw.{{ ansible_hostname }}
    state: started
  when: ansible_distribution == 'Ubuntu'
