---
#########
# SETUP #
#########

# NOTE (leseb): the rbd-mirror daemon needs a user to start
# because it has to authenticate with the local cluster.
# By default, using the admin user is fine, so you should not
# need to change 'ceph_rbd_mirror_local_user' unless you have
# a dedicated key available in /etc/ceph/.
# Generally Ansible will use the admin key and put it
# under /etc/ceph/. The same goes for 'ceph_rbd_mirror_remote_user'
# there should not be any reason to change it.
ceph_rbd_mirror_local_user: admin
ceph_rbd_mirror_remote_user: admin

# NOTE (leseb): the following variable needs the name of the remote cluster.
# The name of this cluster must be different than your local cluster simply
# because we need to have both keys and ceph.conf inside /etc/ceph.
# Thus if cluster names are identical we can not have them under /etc/ceph
ceph_rbd_mirror_remote_cluster: ""

#################
# CONFIGURATION #
#################

ceph_rbd_mirror_configure: false
ceph_rbd_mirror_pool: ""
